[env]
COMPOSE_BAKE = "true"
DOCKER_BUILDKIT = "1"

[tasks.check]
description = "Check the files for issues"
alias = ["c"]
run = "script/trunk check"

[tasks.fix]
description = "Fix any issues in the files"
run = "script/trunk check --fix"

[tasks.format]
description = "Format the files"
alias = ["fmt"]
run = "script/trunk fmt"

[tasks.up]
description = "Start or update"
run = "docker compose up --detach"

[tasks.build]
description = "Build the docker image(s)"
alias = ["b"]
run = "docker compose build --pull | cat"
