#!/usr/bin/env bash

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cmd=(
	docker
	run
	"--rm"
	"--tty"
	"--interactive"
	"--pull=always"
	"--platform=linux/amd64"
	"--volume=${root}/srv/docwhat/:/srv/docwhat/"
	"ghcr.io/docwhat/website:latest"

	sh -c 'apk add rsync && rsync -rav --delete-after /html/ /srv/docwhat/'
)

set -x
exec "${cmd[@]}"

# EOF
